Allow extension builds to fail on master

diff --git a/bin/compile-extensions-common b/bin/compile-extensions-common
--- a/bin/compile-extensions-common
+++ b/bin/compile-extensions-common
@@ -4,6 +4,12 @@ set -o xtrace
 
 phpenv global $VERSION
 
+# Extensions are often not compatible with master, so attempt to build them,
+# but allow failures. For other branches we require extensions to build successfully.
+if [[ ! $VERSION =~ ^master$ ]]; then
+  set -o errexit
+fi
+
 travis_time_start() {
   travis_timer_id=$(printf %08x $(( RANDOM * RANDOM )))
   travis_start_time=$(travis_nanoseconds)
